#include"v.c"//th*omuv t[.gi..efs] o[ar] //mq vq
V(mm,J/=16;j(J,i((5+I)/6,Ez[6]={};h(H,l(6,zl+=A[H*(6*i+l)+h]*X[J*h+j]))l(6,R[J*(6*i+l)+j]=zl))),iH,RAX)
Z2 b[]={3,0,2,0,0,2,3,3},w,o;ZU O[256],Z[30];V(oz,i(256,Oi=i+1)i(30,Zi=(1l<<32)+(64l<<i)))tn(bn,lu(m(64,n<<bt)-1)-6)f(z,cc=Nx%64;if(c)xV[Nx/64]&=I0<c;x)g(u_,~b(36)&x|lu(i)<<31|nx/i<<lu(i)|i)
g(_M,w-=1<<i;*(U*)x=Zi;Zi=x)Ui(M_,Ux=Zi;P(x,w+=1<<i;Zi=*(U*)x;x)Q(i>29)_M(i,M_(i+1))+(64L<<i))f(_o,_M(hx,(U)sx);Ox=o;o=ox;x)tn(o_,Ux=bn(t,n);ii=o;Q(i>>8)o=Oi;Oi=M_(x);x<<54|(U)i<<36|t(8+t,n))
f(_r,63&Ox?(--Ox,x):_o(x))f(r_,Q(!(63&++Ox))x)U(ln,R(tx,n,d0(n<<bx,sr,sx+(i<<bx))),ii,in,Ux)g(_i,mx?ln(i*vx,vx,x):t(tx,$4(bx,xg,0,xi,xj)))i2(iz,3>tx?ix:(int)ex,Ux)i2(mz,(bx?mi:mg)(nx,sx),Ux)
//atom over scan +-*%&|<>=~ !@? #_^
F(M,Q_(5-ta||bx&&5-tx)im=ua;in=vx;$(mx,Qn(n%16))z(x);_a(_x(ma&&mx?u_(m,R_(m%6*n,5,m*n,mm(ux,m,n,sr,sa,sx))):R(5,ma?m:n,(ma?mv:vm)(m,n,sr,sa,sx)))))
G(s,z(x);_x(3>tx?t(tx,(bx?i?si:mi:i?sg:mg)(nx,sx)):a?_a(te(vv(nx,sa,sx))):te((i?se:me)(nx,sx))))G(o3,Qr(ax)Q_(17==a)Q_(1!=a&6!=a|mx)31>i?s(2>a,0,x):X((2>a?sI:mI)(u)))
G(k2,ax?a2(i,a,x):6>i?X(3>tx?iV(i,ia,u):eV(i,ea,u)):Z(1,bx?B3(i-6,ia,u):b3(i-6,ia,u)))f(rr,Qr(mx)Q_(bx&2-bx)Z(tx,(bx?r2:r0)(nx,sr,sx+Nx)))f(v,R(tx,1,*(U*)sr=mx?x:jx))f(_v,_x(_i(0,x)))
G(I3,i-=12;Q_(1<i)$(!ax,P(ma|mx,M(i?x:a,i?a:x)));Q_(2-ta)Qt(i?ta-tx|!ax:2-tx)Qn(i?0:nx<=(ax?ix:mz(x)))_a(ax?i?ti(s2(ix,na,sa)):_i(ix,a):Z(ta,IV(3,sa,u))))
g(T,i>tx?ax?5>i?ti(ix):te(ix):2>tx?T(i,Z(2,ig(u))):Z(5,ei(u)):x)G(e1,x=T(5,x);ax?_v(e1(i,a,v(x))):a?aa?X(dV(ia,u)):_a(X((21>i?RZ:EZ)(sa,u))):14-i?X($4(3&i,sZ,eZ,q_,_q)(u)):Z(2,ie(u)))
g(k1,2>--i?k2(i,0,T(2,x)):9-i?e1(i,0,x):k2(8,0,x))G(i3,x=T(2,x);it=m(ta,tx);ij=12<i;12==i|2<t?k2(2,T(t,j?te(1/(5>ta?ia:ea)):a),T(t,x)):ax?ti(j?ix/ia:ix%ia):X(iV(3,!j*ia<<16|(b(16)+ia)/ia,u)))
G(K2,--i;Q_(aa?2>i-4:ax|!ma^!mx|na-nx|2>i-4&(x(a,bx|1<mz(x))|bx|1<mz(x))|5<i)a=T(m(3>i?2:4>i?5:1,m(ta,tx)),a);x=T(ta,x);aa?k2(i,a,x):_a(X(4>i?3>tx?IV(i,sa,u):EV(i,sa,u):BV(i,sa,u))))
f(tt,Qr(!mx)iI=vx;iJ=ux;Q_(1<<6-bx!=I)u_(I,Z(tx,bx?t2(I,J,sr,sx):t0(I,J,sr,sx))))G(o7,i-=24;Q_(1<i)Qr(ax|!!a*aa)s(i,a?T(5,a):a,a?T(5,x):x))
//list n#_^ [&|<>= !@?#^] |<>=
g(nz,R(tx,i,ih=ix;gz(1<tx?h:(h|=h<<8,h|h<<16),Nr,sr)))Ui(n_,R(2,i,nn(i,sr)))f(s_,Q_(2-nx|2-tx)_x(u_(*xu,n_(*xu*xu[1]))))f(_s,_x(R(2,2,*ru=ux;ru[1]=vx)))
g(v1,$6(i-5,tt(x),rr(x),0,0,0,$7(i-11,(mx?_s:s_)(x),_v(x),0,_x(ti(ux)),0,0,Qr(mx)u_(1,x))))inx(m3,_x(u_(n,R(1,n*n,j(n,b3(L(2,i),3>i?j:n-1-j,n,sr+n*j,sx))))))
g(g1,im=iz(x);6>i?u_(m,nz(m*m,tb(1))):10>i?64<m?0:m3(i-7,m,R(1,m,*rV=I0)):$7(i-11,n_(m),0,R(5,m,jj(m,sr)),0,0,i3(13,te(m),n_(m)),v(x)))g(ez,bn(tx,i)>hx?_x(R(tx,i,d0(Nx,sr,sx))):x+i-nx)
U(d1,cc=(U)d%64;d-=c;s-=c;Vd=c>I0&Vd|c<=I0&Vs;if(n+c>64)d0(n+c-64,d+64,s+64);0,in,sd,ss)F(v2,x=ax?v(x):x;a=aa?v(a):a;Q_(ma|mx)Qt(ta-tx)_x(r(ez(na+nx,a),d1(Nx,sr+Na,sx))))
G(l3,i-=14;Qr(!aa)in=iz(a);ij=n>>31;P(ax,Q_(i|j)nz(n,x))Q_(1<i|mx)n+=j*nx;Qn(n>>31)i^j?_x(ln(n,nx-L(nx,n),x)):n>nx?r(ez(n,x),n=Nx;W(n<Nr)(d1(L(n,Nr-n),sr+n,sr),n*=2)):x+n-nx)
f(__,ax?:63&Ox?Ox--:_($(!tx,i(nx,__(xj)));_o(x)))g_(k_,Z2 a;i|x?px?o_(i,x):$3(i,__(x),r_(x),(U)sx):a?ti(w):(oz(),a=1))G(nt,0)U f0(ss);G(dD,Qt(1-tx)sx[nx]=0;_x(f0(sx)))
G_(k,r(!tx?:18>i>a?(5>i|10==i|15==i?k1:ax?g1:v1)(i,x):!!a&!ta&29>i?:17-i?(10>i?K2:11>i?nt:14>i?aa?i3:I3:17>i?l3:20>i?dD:22>i?e1:29>i?o7:o3)(i,a,x):v2(a,x),$(pr,__(a);__(x))))
