#include"a.h"//t[gie]homn3.5.8(26.6).16.32 com(bpqghi de) &|<>=~.!@?#_^ x[#_^]i
_f(E,2<tx?x:ax?te(ix):X(C(e6,(s6)Ix))+t(1,0))F(S,Qn(ua-ux|va-vx)EE __(mx?R(tx,vx,Qn(vx%16)(ma?mm:vm)(mx,vx/16,sr,sa,sx)):te(sE(sa,P0(x)))))
_F(M,Qn(va-ux)EE __(mx?m_(ma,R(tx,ma*vx,Qn(vx%16)i(ma,vm(mx,vx/16,(i2*)sr+i*vx,a2+i*mx,sx)))):R(tx,ma,P0(x);eR=sr;j(nr,R_=sE(a2+j*nx,x)))))
_f(v,R(tx,1,*rU=x))_g(i_,Uu;VX=sx;J(Nx,P(u=b2(i==Ix),l(nx,16*j|iu(u))))nx)_g(nz,R(tx,i,J(Nr,rV[j]=ix-z2)))_g(_i,tx?t(tx,x2[i]):r_(xU[i]))_Z(R1,if(!tx)i(nx,r_(xU[i])),Ux)
ZU m[24];_g(_M,W-=1<<i;*(U*)x=m[i];m[i]=x)_u(M_,Ux=m[i];P(x,m[i]=*(U*)x;W+=1<<i;x)Qz(24-2<i)_M(i,M_(i+1))+(64L<<i))_Z(om,i(24,m[i]=(U)_+64*b(i))i(1<<8,O[i]=i+1))_f(r_,ax?x:(++ox,x))
U_(tn,ii=hn(t,n);(U)i<<56|t(4+t,(U)r(o,o=O[o];O[r]=M_(i)-(U)_)<<48)|n,it,in)_f(_o,if(!tx)i(nx,_r(xU[i]))_M(hx,(U)sx);ox=o;o=b(8)&x>>48)_f(_r,ax?x:63&ox?(--ox,x):_o(x))
_Z(m6,J(n,R_=X_),in,VR,VX)inx(ln,Qz(!tx)R(tx,n,m6(Nr,sr,sx+((int)(i)<<b[tx]))))_g(_j,mx?ln(i*vx,vx,x):_i(i,x))_g(nd,Qz(mx|!tx)_x(ln(i,nx-i,x)))
_U(m0,im=(U)d%64;if(m)i(m=64-m,*d++=*s++)m6(m(m,n)-m,d,s);n,in,sd,ss)g(nt,mx?m_(i,nt(i*vx,_m(x))):tx?i>nx?_x(R(tx,i,m6(i=Nx,sr,sx);W(i<Nr)i+=m0(l(i,Nr-i),sr+i,sr))):x+i-nx:U(i,_i(j%nx,x)))
G(NN,Qr(!aa)in=ea;ax?nz(n,x):i^n>>31?nd(i?n:ux+n,x):nt(i?ux+n:n,x))F(VV,_x(r(hn(tx,na+nx)>ha?_a(m_(ma?ma+1:0,R(ta,na+nx,R1(a);m6(Na,sr,sa)))):a+((U)!!ma<<32)+nx,R1(x);m0(Nx,sr+Na,sx))))
_F(_I,Qz(ma)Qt(2-tx)iX=sx;_a(ta?t(ta-tx,r(uz(x),j(nr,r2[j]=a2[X_]))):U(nx,_i(X_,a))))F(I_,Qt(!ta|ta-tx)__(0))
G(av,X(3>tx?$3(i,ia+Ix,ia-Ix,ia*Ix):$4(i,ea+Ex,ea-Ex,ea*Ex,a?ea/Ex:_q(Ex))))G(vv,VA=sa;_a(X(3>tx?$3(i,Ia+Ix,Ia-Ix,Ia*Ix):$4(i,Ea+Ex,Ea-Ex,Ea*Ex,Ea/Ex))))G(mv,ma?_x(a):_a(x))g(pe,QZ)
G(Z,if(3==i|2<m(ta,tx))EE ax?aa?2<tx?_x(_i(0,Z(i,a,x=v(x)))):ti($3(i,ia+ix,ia-ix,(a?ia:ix)*ix)):Z(i,$4(i,x,ti(-ix),x,te(1/ex)),a):(aa?av:!!ma^!!mx?mv:vv)(i,a|2-i?a:r_(x),x))
inx(dd,n=(n+65535)/n;X(i6 z=Ix;x(n*z>>16,i?z-i*x:x)))_G(md,!i|2<m(ta,tx)?Z(2,i?te(1/ea):a,x):ax?ti(ix/ia):dd(0,a,x))_G(dm,!i?x:ax?ti(ix%ia):dd(a,a,x))
_G(AA,aa?md(i,a,x):ax?_a(i?ti(i_(x,a)):_j(x,a)):(ma?M:mx?S:i?I_:_I)(a,x))F(_C,Qt(ta-tx)Qz(mx||ma&&va-nx)nx?VV(aa?v(a):a,ax?v(x):x):_x(a))F(C_,QZ)F(_S,QZ)
_f(ff,Qr(!mx)_x(m_(vx,R(tx,nx,))))f(rr,QZ)g(su,QZ)f(uq,QZ)f(sq,QZ)_f(ty,_x(ti(tx)))f(ba,QZ)_f(v_,ax?v(x):!tx|mx?R(0,1,*rU=x):m_(1,x))

//L(1>x)<4>x:-'."1 3 4"  fx|f -x |/g'x_/!#x  
_V(c0,__builtin_ia32_compressqi512_mask(x,z0,a),Ua,Vx)f(dt,Va=I0<(i0)nx&*xV;Uu=b0(48<=a);a=c0(u,a);i(4,wi(a[i]))x)
f(qq,ty(x))//&|<>=...@?#.^
_g(v1,$3(i-4,ff(x),rr(x),10>i?su(i-6,x):$6(i-10,dt(x),ba(x),_x(_j(0,x)),uq(x),_x(ti(ux)),sq(x))))_g(f1,$3(i-17,v_(x),qq(x),ax?ti(10>i?!ix:ex):10>i?X(1&0==Ix):X(C(s6,Ex))-t(1,0)))
_g(a1,Qr(!q4(4,11,13,16))in=ex;9>i?m_(n,nz(n*n,te(1))):R(12>i?2:3,n,VR=sr;J(Nr,R_=$3(i-11>>1,I2|j<<4,(e6)(127<<23|(i6)_P()>>9)-1,C(e6,I2|j<<4)/(e2)n))))G(e1,U(nx,k(i,a,_j(j,x))))
G(R3,P(a,S(a,x))Qz(mx)o3(i,P0(x)))G(E3,_a(e3(i-6,a=aa?a:E(a),E(x))))G(O3,Qz(!pa)P(10>i,(tx?10:4)<a?e1(a,0,x):pe(a,x))P(18==a&&mx,_m(x))ij=a?a-4:2;Qz(!!a&1<a-4|mx)(11>i?o3:s3)(j,x))
G_(k,P(20>i,4>--i?tx?Z(i,a,x):e1(i+1,a,x):a?10>i?QZ:16>i?(12>i?dm:14>i?AA:NN)(i&1,a,x):$3(i-16,C_,_C,_S)(a,x):(q4(9,15,17,18)?f1:ax?a1:v1)(i,x))Qr(ax|!tx)(23>i?R3:29>i?E3:O3)(i-20,a,x))
g_(k_,x?$3(i,_r(x),r_(x),(U)sx):o?ti(W):(P_(),om(),o=1))_f(uz,63&ox?(--ox,m_(mx,tn(tx,nx))):x)
//R(3,1<<ix,VR=sr;i(ix,..))Eb[8];Ec[8];Ez[8];i(8,ci*=zi)i(8,Ee=ci;ci+=bi-e;bi+=e)i(8,R_=bi)i(8,R_=ci)))
