#include"v.b"//reduce(MS) mv vm mm atomic(+-* <>=) uniform(+|\QR) AZ(a*~r x+.y)
G(a2,3>tx|5<i?bc(i,$9(i,b+c,b-c,b*c,0,l(b,c),m(b,c),b<c,b>c,b==c)):bc(e,$6(i,b+c,b-c,b*c,b/c,l(b,c),m(b,c))))
#define ft(m,o,O,t,T) T##f(O##t,i(6-m,x=O##T(x,S##m(i,x)))x)i2(o##t,O##t(r(z0,i(m?n4(n):n6(n),r=O##T(r,Xi))))[b(6-m)],in,IX)V(o##T,Iz=z2;r4(z=O##T(z[15]-z2,O##t(Xi))),U3)
#define b4(g,a,b,Y...) e2(g,Se(r(ze,n=n4(n);Ez[4]={};i(n/4,i(4,zi+=a*X++))i(n%4,r+=b Xi)i(4,r+=zi)))[15],Y)
b4(se,,,in,EX)b4(vv,*A++*,Ai*,in,EA,EX)ft(0,m,M,g,G)ft(2,m,M,i,I)ft(2,s,S,i,I)e2(me,ii=mi(n,X);*(e2*)&i,in,EX)i2(s2,i(n4(n),Ub=b2(m==Ri);P(b,16*i|iu(b)))n,im,in,IR)
#define M2(K) h(8/K,ik=K;j(k,ii=2*h*k+j;Ri=_P(Xi,r(Xk,Rk=P_(Xi,r)))))
V(f2,h(m/16,i(n/16,M2(1)X=R;M2(2)M2(4)M2(8))),im,U3)V(ZZ,i(n3(n),Ri=JI(X5)<<m*32),im,U3)R4(zz,4>m?m?x(*X++,$3(m-i,AZ,_P,P_)(x,*X++)):IG(X4):5>m?EI(Xi):$4(m-5,IE,q,L,E)(Xi),im,U3)
R6(d0,Xi,U3)R6(z6,1&$3(m,c<Xg,c>Xg,c==Xg),im,cc,U3)R6(gz,m-z2,im,in,IR)R4(z4,$3(m,I2|16*i,JJ(),EI(I2|16*i)/(e2)n),im,in,IR)R4(r2,*--X,U3)R4(e4,$4(m,e+Xe,e-Xe,e*Xe,e/Xe),im,ee,U3)
R4(i4,$5(m,j+Xi,j-Xi,j*Xi,x((i1)j*Xi>>16,j>>16?Xi-(j>>16)*x:x),1&GI($3(m-6,j<X8,j>X8,j==X8))),im,ij,U3)R4(I4,$7(m,Ai+Xi,Ai-Xi,Ai*Xi,Ae+Xi,Ae-Xe,Ae*Xi,G2(A,Xi)),im,IA,U3)
V(SV,ee=me(n,X);r4(E(Xe-e))e=1/se(n,R);r4(e*Re),U3)V(RV,ee=1/q(vv(n,X,X)/n-ze)[0];r4(e*Ae*Xe),EA,U3)R4(EV,Ae*Xi/(1+E(-Xi)),EA,U3)
g6(q8,*e=2.3;GI(x),e2*e,i8 x)e2(v8,Se(r(ze,i(n,r+=Ri*d8(Ai,Xi))))[15],eR,EA,in,EX)
#define e5 im,eA,in,eR,EX
#define E5 im,EA,in,ER,EX
V(mv,i(m,Ri=vv(n,A+n*i,X)),e5)V(qv,g6 z[n/=64];i(n,zi=q8(A,X8))i(m,Ri=v8(A+n*i,A+m*n/4+n*i,n,z)),e5)
V(vm,n=n4(n);i(n/4,Ez[4]={};h(m,i(4,zi+=A[h]*X[n*h+i]))X+=4;i(4,*R++=zi))i(n%4,Ri=r(ze,i(m,r+=Ai*X[n*i])++X)),E5)V(mm,i(h,vm(m,A+n/16*i,n,R+n/16*i,X)),ih,E5)
